# Generated by Django 5.2.1 on 2026-04-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicclass',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='academicclass',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='staffattendance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staffattendance',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subjectassignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subjectassignment',
            name='updated_at',
        ),
    ]
