# Generated by Django 5.2.1 on 2026-04-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_academicclass_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='department',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='mobile',
        ),
    ]
