# Generated by Django 5.2.1 on 2026-04-09 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_faculty_department_remove_faculty_mobile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='core.academicclass'),
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='core.faculty'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mark',
            name='exam_type',
            field=models.CharField(choices=[('Class Test', 'Class Test'), ('Mid Exam', 'Mid Exam'), ('Assignment', 'Assignment'), ('Practical', 'Practical'), ('Internal', 'Internal'), ('Midterm', 'Midterm'), ('Final', 'Final')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'subject', 'date')},
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('due_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_list', to='core.subject')),
            ],
            options={
                'ordering': ['due_date', 'title'],
                'unique_together': {('subject', 'title', 'due_date')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('marks', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.student')),
            ],
            options={
                'ordering': ['assignment__due_date', 'student__name'],
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
