# Generated by Django 5.2.1 on 2026-04-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_studentattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='exam_type',
            field=models.CharField(choices=[('Class Test', 'Class Test'), ('Mid Exam', 'Mid Exam'), ('Assignment', 'Assignment'), ('Internal', 'Internal'), ('Midterm', 'Midterm'), ('Final', 'Final')], max_length=30),
        ),
    ]
