# Generated by Django 5.2.1 on 2026-04-15 09:13

import django.db.models.deletion
from django.db import migrations, models


def deduplicate_subject_assignments(apps, schema_editor):
    SubjectAssignment = apps.get_model("core", "SubjectAssignment")
    assignments = SubjectAssignment.objects.order_by("subject_id", "id")
    seen_subject_ids = set()
    duplicate_ids = []

    for assignment in assignments:
        if assignment.subject_id in seen_subject_ids:
            duplicate_ids.append(assignment.id)
        else:
            seen_subject_ids.add(assignment.subject_id)

    if duplicate_ids:
        SubjectAssignment.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mark_exam_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester_label',
        ),
        migrations.RunPython(deduplicate_subject_assignments, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='subjectassignment',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='core.subject'),
        ),
    ]
